import { Geist, Geist_Mono ,Playfair_Display } from "next/font/google";
import "./globals.css";
// Configure the font
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Include only the necessary weights
  variable: '--font-playfair', // Custom CSS variable (optional)
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
